# Generated by Django 6.0.2 on 2026-02-09 12:20

from django.db import migrations


def populate_rooms(apps, schema_editor):
    """Create 30 rooms (Room 1 through Room 30)."""
    Room = apps.get_model('rooms', 'Room')
    for i in range(1, 31):
        Room.objects.get_or_create(
            room_number=str(i),
            defaults={'is_active': True}
        )


def reverse_populate_rooms(apps, schema_editor):
    """Remove all rooms."""
    Room = apps.get_model('rooms', 'Room')
    Room.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_rooms, reverse_populate_rooms),
    ]
