# Generated by Django 4.2.28 on 2026-06-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Room', 'verbose_name_plural': 'Reservations'},
        ),
    ]
