# Generated by Django 4.2.28 on 2026-05-20 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktrackReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('voucher_number', models.CharField(blank=True, max_length=100, null=True)),
                ('room_number', models.CharField(max_length=10)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Backtrack Reservation',
                'verbose_name_plural': 'Backtrack Reservations',
                'ordering': ['-check_in_date'],
            },
        ),
        migrations.CreateModel(
            name='BacktrackVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_file', models.FileField(upload_to='backtrack_vouchers/')),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('voucher_number', models.CharField(blank=True, max_length=100)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('check_in_raw', models.CharField(blank=True, max_length=50)),
                ('check_out_raw', models.CharField(blank=True, max_length=50)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='backtrack.backtrackreservation')),
            ],
            options={
                'verbose_name': 'Backtrack Voucher',
                'verbose_name_plural': 'Backtrack Vouchers',
                'ordering': ['-created_at'],
            },
        ),
    ]
